import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { GeistSans } from "geist/font/sans";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Providers from "@/components/Providers";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SessionProvider session={session}>
          <Providers>
            <Header />
            <main /* className={fontVars} */>{children}</main>
            <Footer />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
